services:
  - type: static
    name: ceit-metaverse-frontend
    branch: vresion-2.1
    staticPublishPath: WebPage
    buildCommand: echo "no build"
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: ceit-metaverse-backend
    branch: vresion-2.1
    runtime: node
    buildCommand: cd Script/DataBase && npm install && npx prisma generate --schema=./prisma/schema.prisma && npx prisma migrate deploy --schema=./prisma/schema.prisma
    startCommand: cd Script/DataBase && node sever.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
